import type { Field } from "./model";

// Explicit equivalents only: avoid guessing from typos or unrelated questions.
export const alternateLabels: Partial<Record<Field, string[]>> = {
  gender: ["gender identity", "applicant gender"],
  city: [
    "location city",
    "current city", "city of residence", "residing city", "city town",
    "which city do you live in", "which city are you based in",
  ],
  currentLocation: [
    "current location", "present location", "where are you located",
    "where you located", "now where you are located", "where are you currently located",
    "where u located", "where are u located",
    "where are you located now", "where do you currently live", "where do you live",
    "where are you based", "where are you currently based", "current place of residence",
  ],
  country: ["country of residence", "residing country", "current country"],
  experience: [
    "employment history", "professional experience", "work history",
    "work experience details", "describe your work experience", "previous work experience",
    "past work experience", "professional background", "employment background",
    "describe your employment history", "previous employment details", "career history",
    "work background",
  ],
  internships: [
    "internship details",
    "internship experience",
    "internship history",
  ],
  aboutYou: [
    "professional summary",
    "personal summary",
    "brief introduction",
    "introduce yourself",
  ],
  whyHire: [
    "why should you be hired",
    "why are you suitable for this role",
    "why are you a good fit",
  ],
  whyCompany: [
    "why do you want to join our company",
    "why do you want to join us",
  ],
  availability: [
    "interview availability", "availability for interview",
    "how quickly can you join us", "how quickly can you join", "how soon can you join us",
    "when can you join us", "when can you join", "when are you available to join",
    "how soon can you start", "how quickly can you start", "when can you start work",
    "when are you available to start", "how soon are you available", "joining availability",
    "how soon could you join", "when would you be able to join",
  ],
  tenthSchool: ["10th school name", "secondary school name", "school name ssc"],
  tenthBoard: ["secondary education board", "matriculation board"],
  tenthYear: [
    "10th year of passing",
    "ssc year of passing",
    "sslc year of passing",
    "secondary school passing year",
  ],
  tenthPercentage: [
    "10th marks percentage",
    "ssc marks percentage",
    "secondary school percentage",
  ],
  preDegreeType: ["higher secondary or diploma", "12th or diploma"],
  preDegreeCollege: [
    "which high school did you go to 12th grade",
    "which school did you attend for 12th grade",
    "where did you complete your 12th",
    "where did you study in class 12",
    "name of your 12th grade school",
    "12th grade school", "class 12 school", "school attended for 12th",
    "higher secondary institution", "higher secondary school attended",
    "senior secondary school name", "hsc school name", "puc institution name",
    "higher secondary school name",
    "12th school name",
    "pre university college",
    "diploma institute name",
  ],
  preDegreeBoard: [
    "higher secondary board",
    "pre university board",
    "diploma board",
  ],
  preDegreeYear: [
    "12th year of passing",
    "diploma year of passing",
    "puc year of passing",
    "higher secondary passing year",
  ],
  preDegreePercentage: [
    "higher secondary percentage",
    "12th marks percentage",
    "diploma marks percentage",
  ],
  educationStartYear: [
    "degree admission year",
    "degree enrollment year",
    "graduation commencement year",
  ],
  degreePercentage: [
    "degree aggregate percentage",
    "bachelor degree percentage",
    "undergraduate percentage",
  ],
  studyType: [
    "study mode",
    "course mode",
    "mode of education",
    "full time part time",
  ],
  backlogs: [
    "current backlogs",
    "pending backlogs",
    "active arrears",
    "number of backlogs",
  ],
  educationGap: ["academic gap in months", "gap in education months"],
  nationality: ["country of citizenship", "applicant nationality"],
  employmentStatus: [
    "experience level fresher experienced",
    "candidate type fresher experienced",
  ],
  joiningDate: [
    "earliest joining date",
    "date available to join",
    "date of availability",
    "earliest start date",
  ],
  relocate: [
    "are you willing to relocate",
    "relocation willingness",
    "ready to relocate",
  ],
  workShifts: [
    "open to working shifts",
    "ready to work in shifts",
    "willing to work in rotational shifts",
  ],
  workMode: ["preferred work mode", "preferred working arrangement"],
  currentSalary: ["present ctc", "present salary", "current compensation"],
  programmingLanguages: ["coding languages", "programming language skills"],
  tools: ["software tools", "developer tools"],
  projectTitle: ["academic project title", "final year project name"],
  projectDescription: [
    "project overview",
    "describe your project",
    "project abstract",
  ],
  projectContribution: [
    "role in project",
    "your role in the project",
    "project responsibilities",
  ],
  projectTechnologies: [
    "technologies used in project",
    "project technology stack",
  ],
  projectGithub: [
    "project github link",
    "project source code url",
    "project repository url",
  ],
  projectDemo: [
    "project live link",
    "project demo link",
    "project deployment url",
  ],
  certifications: [
    "professional certifications",
    "certification details",
    "certificates and courses",
  ],
  codingProfile: [
    "competitive programming profile",
    "leetcode profile",
    "hackerrank profile",
    "coding profile link",
  ],
  workAuthorization: [
    "do you have authorization to work in india",
    "eligible to work in india",
  ],
  visaSponsorship: [
    "do you need visa sponsorship",
    "will you need visa sponsorship",
    "need visa sponsorship",
  ],
  previouslyApplied: [
    "have you previously applied to our company",
    "applied to this company previously",
  ],
  fullName: [
    "candidate name",
    "candidate full name",
    "applicant full name",
    "name of applicant",
    "name of candidate",
    "legal name",
  ],
  firstName: ["forename", "firstname", "fname", "given names"],
  lastName: ["lastname", "lname", "sur name"],
  email: [
    "email addr",
    "email add",
    "electronic mail address",
    "applicant email address",
    "candidate email id",
    "preferred email address",
    "contact email id",
    "emailid",
    "emailaddress",
    "mail id",
    "mail address",
    "primary email",
    "personal email",
    "contact email",
    "email id address",
  ],
  mobile: [
    "phone num",
    "mobile num",
    "telephone num",
    "contact num",
    "cellphone no",
    "cellular telephone number",
    "personal telephone number",
    "applicant contact number",
    "candidate contact number",
    "preferred contact number",
    "mobile phone",
    "mobile phone number",
    "mobile telephone number",
    "cellular phone",
    "cellular number",
    "cellular phone number",
    "cellphone number",
    "cell phone number",
    "cell no",
    "telephone no",
    "tel no",
    "tel number",
    "mob no",
    "mob number",
    "contact telephone",
    "contact telephone number",
    "contact phone",
    "contact phone number",
    "contact mobile number",
    "applicant phone number",
    "candidate mobile number",
    "personal mobile number",
    "primary mobile",
    "primary mobile number",
    "primary telephone number",
    "main phone number",
    "phonenumber",
    "mobilenumber",
    "contactnumber",
    "telephonenumber",
    "cellphonenumber",
    "telno",
    "mobno",
    "mobile no",
    "phone no",
    "contact no",
    "telephone",
    "telephone number",
    "cell phone",
    "cellphone",
    "cell number",
    "contact mobile",
    "mobileno",
    "phoneno",
    "primary phone",
    "primary contact number",
  ],
  dob: ["birth date", "birthdate", "dateofbirth", "date of birth dd mm yyyy"],
  currentAddress: [
    "current residential address",
    "present residential address",
    "address for correspondence",
    "current mailing address",
    "present address",
    "residential address",
    "residence address",
    "correspondence address",
    "mailing address",
    "street address line 1",
  ],
  permanentAddress: [
    "permanent mailing address",
    "permanent home address",
    "permanent residential address",
    "permanent residence address",
  ],
  postalCode: [
    "postal zip code",
    "zip postal code",
    "postal pin code",
    "pin postal code",
    "postcode",
    "post code",
    "postalcode",
    "zipcode",
    "area pin code",
  ],
  state: ["state ut", "state union territory", "region province"],
  degree: [
    "degree obtained",
    "degree awarded",
    "highest degree earned",
    "academic qualification",
    "highest qualification",
    "highest educational qualification",
    "degree name",
    "qualification name",
  ],
  branch: [
    "area of specialization",
    "area of specialisation",
    "degree specialization",
    "degree discipline",
    "academic major",
    "specialisation",
    "discipline",
    "field of study",
    "stream",
    "engineering branch",
    "course specialisation",
  ],
  college: [
    "educational institution name",
    "graduating college",
    "degree college name",
    "institute name",
    "name of institution",
    "name of college",
    "college institute name",
  ],
  graduationYear: [
    "degree completion year",
    "degree passing year",
    "year graduated",
    "year of degree completion",
    "year of passing",
    "passing year",
    "year of completion",
    "graduation passing year",
    "yop",
  ],
  cgpa: [
    "cumulative grade point average", "overall cgpa", "aggregate cgpa",
    "grade point average", "cumulative gpa", "overall gpa", "college gpa",
    "degree cgpa", "graduation cgpa", "undergraduate gpa", "academic gpa",
    "final cgpa", "what is your gpa", "what is your cgpa",
  ],
  skills: [
    "technical competencies",
    "technical skill set",
    "professional skills",
    "relevant technical skills",
    "technical skills",
    "key skills",
    "primary skills",
    "skillset",
    "core skills",
  ],
  technologies: [
    "tools and technologies",
    "technology stack",
    "technical stack",
  ],
  portfolio: ["portfolio link", "portfolio website", "personal site"],
  github: ["github profile", "github link", "github profile url"],
  linkedin: ["linkedin profile", "linkedin link", "linkedin profile url", "linkedln profile"],
  preferredRole: [
    "role s you wish to apply to", "roles you wish to apply to", "role you wish to apply to",
    "which role are you applying for", "which position are you applying for",
    "what role would you like to apply for", "what position are you interested in",
    "roles of interest", "position of interest", "role of interest",
    "which roles interest you", "job you are applying for",
    "position applying for",
    "role applying for",
    "desired job title",
    "preferred position",
    "position applied for",
    "role applied for",
    "applying for role",
    "desired role",
    "preferred job role",
  ],
  preferredLocation: [
    "preferred city of employment",
    "preferred work city",
    "desired work location",
    "preferred work location",
    "preferred job location",
    "location preference",
  ],
  expectedSalary: [
    "ctc expectation",
    "expected remuneration",
    "salary expectations",
    "desired compensation",
    "expected ctc",
    "salary expected",
    "desired salary",
    "expected compensation",
  ],
  university: [
    "name of university",
    "affiliating university",
    "affiliated university",
  ],
  noticePeriod: ["notice duration", "notice period days"],
  totalExperience: [
    "years of experience",
    "total years of experience",
    "total work experience in years",
  ],
};
